<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DevMap.Mapster" Version="9.2.3-alpha" />
    <PackageReference Include="DevMap.Mapster.DependencyInjection" Version="9.2.2-alpha" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.9" />
  </ItemGroup>

</Project>
